# Site settings
url: http://daniel-mejia.com

# Jekyll-assets configuration
assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  cdn: 
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: false
    automatic_img_size: true
    automatic_img_alt : true



environment: production