url: http://127.0.0.1:4000/

# Plugin: jekyll-assets

assets:
  cache: false

environment: development



# Plugin: jekyll assets
assets:
  compress:
    css: false
    js: false
  cache: .asset-cache
  prefix: "/assets"
  assets:
    - "app.js"
    - "app.css"
  digest: false
  sources:
    - _assets/css
    - _assets/js
    - _assets/fonts
    - _assets/img
    - _assets/img/*.svg
    - _assets/img/*.png
    - _assets/img/**/*.jpg
    - _assets/img/**/*.png
  features:
    liquid: false
    automatic_img_size: true
    automatic_img_alt : true

environment: development



