# Site settings
title: Daniel Mejía
email: design@daniel-mejia.com
description: "Daniel Mejía is a graphic and web designer based in Puerto Rico. Who specialises in brand development, web design and social media marketing." # the base hostname & protocol for your site
url: http://daniel-mejia.com
logo_path: img/logos/dm-color-logo.svg
year: 2016
timezone: America/Puerto_Rico


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF818F 
  secondary: 50A5DC 
  secondary-dark: 27627D 

# Plugins
#gems: [jekyll-paginate]
#paginate: 3
#paginate_path: "/blog/page:num/"
gems:
  - jekyll-redirect-from
  - jekyll-assets

# Build settings
markdown: kramdown
permalink: pretty

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Daniel Mejía 
      layout: "post"
      category: design
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/_daniel_mejia
  - title: facebook
    url: https://www.facebook.com/l.daniel.mejia
  - title: instagram
    url: https://www.instagram.com/_daniel_mejia/
  - title: pinterest
    url: https://www.pinterest.com/ldanielmejia/
#  - title: flickr
#    url: https://www.flickr.com/
#  - title: stack-overflow
#    url: http://stackoverflow.com/users/4505357/daniel-mej%C3%ADa
#  - title: bitbucket 
#    url: https://bitbucket.org/daniel-mejia/
#  - title: github
#    url: https://github.com/daniel-mejia
#  - title: behance
#    url: https://www.behance.net/danielmeji1498
#  - title: codepen
#    url: http://codepen.io/daniel-mejia/

assets:
  compress:
    css: false
    js: false
  cache: .asset-cache
 
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.css"
    - "*.js"
  digest: false
  sources:
    - _includes/css
    - img
    - img/about
    - img/portfolio
    - js
    - css/font-awesome/fonts
  features:
    liquid: false
    automatic_img_size: true
    automatic_img_alt : true